server:
  port: 8081

# General Config
spring:
    data:
        mongodb:
          uri: ${MONGODB_URI}
          database: ${MONGODB_DATABASE}

logging:
  level:
    com: 
      lsoftware:
        voting: info